services:

  python_server:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "65432:65432"
    volumes:
      - ./app:/serverPython
    restart: unless-stopped
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8080:80"
    volumes:
      - ./apache:/var/www/html:ro
    restart: unless-stopped